resource/urls.py
# Copyright (c) 2017-2020 Neogeo-Technologies.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


from django.conf.urls import url

from resource.views import CreateResourceStore
from resource.views import DeleteResourceStore
from resource.views import EditResourceStore
from resource.views import EmitResourceStore
from resource.views import GoForResource
from resource.views import RedirectResource
from resource.views import ShowDirectoryStorage
from resource.views import ShowDirectoryStorageGlob
from resource.views import ShowResourceStore
from resource.views import UpdateResourceStore


urlpatterns = [
    url('^dataset/(?P<dataset_id>(\d+))/-/resource/$', RedirectResource.as_view(), name='redirect_resource'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/$', GoForResource.as_view(), name='go_for_resource'),

    # Resource: Store
    # ===============
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/store/$', EmitResourceStore.as_view(), name='emit_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/store/create/$', CreateResourceStore.as_view(), name='create_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/show/$', ShowResourceStore.as_view(), name='show_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/edit/$', EditResourceStore.as_view(), name='edit_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/update/$', UpdateResourceStore.as_view(), name='update_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/delete/$', DeleteResourceStore.as_view(), name='delete_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/directory/$', ShowDirectoryStorage.as_view(), name='directory_storage'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/directory/(?P<glob_path>(.+))/?$', ShowDirectoryStorageGlob.as_view(), name='directory_storage_glob'),
]

resource/views/go_for.py
# Copyright (c) 2017-2020 Neogeo-Technologies.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


from django.conf import settings
from django.contrib.auth.decorators import login_required
# from django.db import transaction
# from django.http import Http404
# from django.shortcuts import get_object_or_404
# from django.shortcuts import redirect
# from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views import View
# from idgo_admin.exceptions import ExceptionsHandler
# from idgo_admin.exceptions import ProfileHttp404
from idgo_admin.models import Dataset
from idgo_admin.shortcuts import get_object_or_404_extended
# from idgo_admin.shortcuts import on_profile_http404
from idgo_admin.shortcuts import render_with_info_profile
from idgo_admin.shortcuts import user_and_profile
# from idgo_admin.views.dataset import target as datasets_target
# from resource import logger
# from resource.models import Resource


# CKAN_URL = settings.CKAN_URL
#
# FTP_DIR = settings.FTP_DIR
# try:
#     FTP_UPLOADS_DIR = settings.FTP_UPLOADS_DIR
# except AttributeError:
#     FTP_UPLOADS_DIR = 'uploads'


decorators = [csrf_exempt, login_required(login_url=settings.LOGIN_URL)]


@method_decorator(decorators, name='dispatch')
class GoForResource(View):

    def get(self, request, dataset_id=None, *args, **kwargs):
        user, profile = user_and_profile(request)
        dataset = get_object_or_404_extended(Dataset, user, include={'id': dataset_id})
        context = {'dataset': dataset}
        return render_with_info_profile(request, 'resource/go_for.html', context)

    # def post(self, request, dataset_id=None, *args, **kwargs):
    #     # redirect to resource children app:
    #     app = request.POST.get('app', request.GET.get('app'))
    #     if app:
    #         return redirect(self.resource_router(dataset_id, app, action='create'))


# @method_decorator(decorators, name='dispatch')
# class ResourceManager(View):
#     template = 'resource/resource.html'
#
#     def get_context(self, form, user, dataset, resource=None):
#         return {
#             'target': datasets_target(dataset, user),
#             'dataset': dataset,
#             'resource': resource,
#             'form': form,
#             }
#
#     def resource_router(self, dataset_id, app, instance_id=None, action='create'):
#         from django.apps import apps
#         from django.urls.exceptions import NoReverseMatch
#         if apps.is_installed(app):
#             url_pattern = "{0}:resource-{0}-{1}".format(app, action)
#             kvp = {'dataset_id': dataset_id}
#             if action == 'update':
#                 kvp['pk'] = instance_id
#             return reverse(url_pattern, kwargs=kvp)
#         else:
#             raise NoReverseMatch
#
#     @ExceptionsHandler(actions={ProfileHttp404: on_profile_http404})
#     def get(self, request, dataset_id=None, *args, **kwargs):
#
#         user, profile = user_and_profile(request)
#
#         dataset = get_object_or_404_extended(
#             Dataset, user, include={'id': dataset_id})
#         # redirect to resource children app:
#         app = request.POST.get('app', request.GET.get('app'))
#         if app:
#             return redirect(self.resource_router(dataset_id, app, action='create'))
#         # Redirect to layer
#         # _resource = request.GET.get('resource')
#         # _layer = request.GET.get('layer')
#         # if _resource and _layer:
#         #     return redirect(
#         #         reverse('idgo_admin:layer_editor', kwargs={
#         #             'dataset_id': dataset.id,
#         #             'resource_id': _resource,
#         #             'layer_id': _layer}))
#         #
#         # resource = None
#         # id = request.GET.get('id')
#         # if id:
#         #     include = {'id': id, 'dataset_id': dataset.id}
#         #     resource = get_object_or_404_extended(Resource, user, include=include)
#
#         # form = Form(instance=resource)
#         context = self.get_context(None, user, dataset, resource=resource)
#         return render_with_info_profile(request, self.template, context)
#
#     @ExceptionsHandler(ignore=[Http404], actions={ProfileHttp404: on_profile_http404})
#     @transaction.atomic
#     def post(self, request, dataset_id=None, *args, **kwargs):
#         user, profile = user_and_profile(request)
#         dataset = get_object_or_404_extended(
#             Dataset, user, include={'id': dataset_id})
#         form = Form(request.POST, request.FILES)
#         if form.is_valid():
#
#             try:
#                 resource = form.save()
#             except Exception:
#                 logger.excption('ResourceManager:post')
#             else:
#                 app = request.POST.get('app')
#                 return redirect(self.resource_router(dataset_id, app, action='create'))
#
#         context = self.get_context(form, user, dataset, resource)
#         return render_with_info_profile(request, self.template, context)


# @login_required(login_url=settings.LOGIN_URL)
# @csrf_exempt
# def resource(request, dataset_id=None, *args, **kwargs):
#     user, profile = user_and_profile(request)
#
#     id = request.GET.get('id', request.GET.get('ckan_id'))
#     if not id:
#         raise Http404()
#
#     kvp = {}
#     try:
#         id = int(id)
#     except ValueError:
#         kvp['ckan_id'] = id
#     else:
#         kvp['id'] = id
#     finally:
#         resource = get_object_or_404(Resource, **kvp)
#
#     # TODO:
#     # return redirect(reverse('idgo_admin:resource_editor', kwargs={
#     #     'dataset_id': resource.dataset.id, 'resource_id': resource.id}))
#     return redirect(
#         '{}?id={}'.format(
#             reverse(
#                 'resource:resource', kwargs={'dataset_id': resource.dataset.id}),
#             resource.id))

resource/views/resource.py
# Copyright (c) 2017-2020 Neogeo-Technologies.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


from django.conf import settings

from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from idgo_admin.shortcuts import user_and_profile
from resource.models import Resource


decorators = [csrf_exempt, login_required(login_url=settings.LOGIN_URL)]


@method_decorator(decorators, name='dispatch')
class ShowResource(View):
    """Voir une resource."""


@method_decorator(decorators, name='dispatch')
class RedirectResource(View):
    """Rediriger vers la resource."""

    def get(self, request, dataset_id=None, *args, **kwargs):
        user, profile = user_and_profile(request)

        id = request.GET.get('id', request.GET.get('ckan_id'))
        if not id:
            raise Http404()

        kwargs = {}
        try:
            id = int(id)
        except ValueError:
            kwargs['ckan_id'] = id
        else:
            kwargs['id'] = id
        resource = get_object_or_404(Resource, **kwargs)

        if hasattr(resource, 'store'):
            namespace = 'resource:show_resource_store'
        else:
            raise Http404()

        url = reverse(namespace, kwargs={'dataset_id': resource.dataset.pk, 'resource_id': resource.pk})
        return redirect(url)

resource/templates/resource/create.html
{% extends "idgo_admin/base.html" %}

{% load bootstrap3 %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
  {% include "resource/breadcrumb_base.html" %}
  <li class="active">
    Nouvelle ressource
  </li>
</ol>
{% endblock breadcrumb_content %}

{% block main_content %}
{% include "idgo_admin/alert_messages.html" %}
<form method="post" action="{% url 'resource:create_resource_store' dataset_id=dataset.id %}" class="well">
  {% csrf_token %}
  <div class="row">
    <div class="col-xs-12">
      {% bootstrap_field form.title %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      {% bootstrap_field form.description %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.language %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.resource_type %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.format_type %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 hidden">
      {% bootstrap_field form.redis_key %}
    </div>
  </div>
  <br />
  <div class="buttons-on-the-right-side">
    <a class="btn btn-default" href="{% url 'idgo_admin:dataset' %}?id={{ dataset.id }}#resources">Annuler</a>
    <button type="submit" class="btn btn-default">Valider la création</button>
  </div>
  <hr />
  <small>* Les champs marqués d'un astérisque sont obligatoires.</small>
</form>
{% endblock main_content %}

resource/templates/resource/edit.html
{% extends "idgo_admin/base.html" %}

{% load bootstrap3 %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
  {% include "resource/breadcrumb_base.html" %}
  <li>{{ resource.title }}</li>
  <li class="active">Editer la ressource</li>
</ol>
{% endblock breadcrumb_content %}

{% block main_content %}
{% include "idgo_admin/alert_messages.html" %}
<form method="post" action="{% url 'resource:edit_resource_store' dataset_id=dataset.id resource_id=resource.id%}" class="well">
  {% csrf_token %}
  <div class="row">
    <div class="col-xs-12">
      {% bootstrap_field form.title %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      {% bootstrap_field form.description %}
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.language %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.resource_type %}
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.format_type %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 hidden">
      {% bootstrap_field form.redis_key %}
    </div>
  </div>
  <br />
  <div class="buttons-on-the-right-side">
    <a class="btn btn-default" href="{% url 'idgo_admin:dataset' %}?id={{ dataset.id }}#resources">Annuler</a>
    <button type="submit" class="btn btn-default">Valider la modification</button>
  </div>
  <hr />
  <small>* Les champs marqués d'un astérisque sont obligatoires.</small>
</form>
{% endblock main_content %}

resource/templates/resource/go_for.html
{% extends "idgo_admin/base.html" %}

{% load bootstrap3 %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
  {% include "resource/breadcrumb_base.html" %}
  <li class="active">
    Ajouter une ressource
  </li>
</ol>
{% endblock breadcrumb_content %}

{% block main_content %}
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="list-group">
      <a href="#" class="list-group-item disabled">
        <h4 class="list-group-item-heading">Téléverser un fichier</h4>
        <p class="list-group-item-text">

        </p>
      </a>
      <a href="#" class="list-group-item disabled">
        <h4 class="list-group-item-heading">Synchroniser une URL de donnnées</h4>
        <p class="list-group-item-text">

        </p>
      </a>
      <a href="#" class="list-group-item disabled">
        <h4 class="list-group-item-heading">Synchroniser un fichier depuis le FTP</h4>
        <p class="list-group-item-text">

        </p>
      </a>
      <a href="{% url 'resource:emit_resource_store' dataset_id=dataset.id %}" class="list-group-item list-group-item-success">
        <h4 class="list-group-item-heading">Téléverser un répertoire de fichiers</h4>
        <p class="list-group-item-text">

        </p>
      </a>
      <a href="#" class="list-group-item disabled">
        <h4 class="list-group-item-heading">Référencer une URL</h4>
        <p class="list-group-item-text">

        </p>
      </a>
    </div>
  </div>
</div>
{% endblock main_content %}