resource/urls.py
# Copyright (c) 2017-2020 Neogeo-Technologies.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


from django.conf.urls import url

from resource.views import CreateResourceStore
from resource.views import DeleteResourceStore
from resource.views import EditResourceStore
from resource.views import EmitResourceStore
from resource.views import GoForResource
from resource.views import RedirectResource
from resource.views import ShowDirectoryStorage
from resource.views import ShowDirectoryStorageGlob
from resource.views import ShowResourceStore
from resource.views import UpdateResourceStore


urlpatterns = [
    url('^dataset/(?P<dataset_id>(\d+))/-/resource/$', RedirectResource.as_view(), name='redirect_resource'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/$', GoForResource.as_view(), name='go_for_resource'),

    # Resource: Store
    # ===============
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/store/$', EmitResourceStore.as_view(), name='emit_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/store/create/$', CreateResourceStore.as_view(), name='create_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/show/$', ShowResourceStore.as_view(), name='show_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/edit/$', EditResourceStore.as_view(), name='edit_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/update/$', UpdateResourceStore.as_view(), name='update_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/delete/$', DeleteResourceStore.as_view(), name='delete_resource_store'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/directory/$', ShowDirectoryStorage.as_view(), name='directory_storage'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/store/directory/(?P<glob_path>(.+))/?$', ShowDirectoryStorageGlob.as_view(), name='directory_storage_glob'),
]

resource/views/resource.py
# Copyright (c) 2017-2020 Neogeo-Technologies.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


from django.conf import settings

from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from idgo_admin.shortcuts import user_and_profile
from resource.models import Resource


decorators = [csrf_exempt, login_required(login_url=settings.LOGIN_URL)]


@method_decorator(decorators, name='dispatch')
class ShowResource(View):
    """Voir une resource."""


@method_decorator(decorators, name='dispatch')
class RedirectResource(View):
    """Rediriger vers la resource."""

    def get(self, request, dataset_id=None, *args, **kwargs):
        user, profile = user_and_profile(request)

        id = request.GET.get('id', request.GET.get('ckan_id'))
        if not id:
            raise Http404()

        kwargs = {}
        try:
            id = int(id)
        except ValueError:
            kwargs['ckan_id'] = id
        else:
            kwargs['id'] = id
        resource = get_object_or_404(Resource, **kwargs)

        if hasattr(resource, 'store'):
            namespace = 'resource:show_resource_store'
        else:
            raise Http404()

        url = reverse(namespace, kwargs={'dataset_id': resource.dataset.pk, 'resource_id': resource.pk})
        return redirect(url)

resource/views/store.py
# Copyright (c) 2017-2020 Neogeo-Technologies.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import io
import json
from functools import reduce
import magic
from mimetypes import MimeTypes
from operator import ior
import os
import os.path
import pathlib
from urllib.parse import urljoin

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.db import transaction
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse  # from django.urls import reverse

from idgo_admin.ckan_module import CkanHandler
from idgo_admin.ckan_module import CkanUserHandler
from idgo_admin.models import Dataset
from idgo_admin.shortcuts import get_object_or_404_extended
from idgo_admin.shortcuts import render_with_info_profile
from idgo_admin.shortcuts import user_and_profile
from resource.forms import CreateResourceStoreForm
from resource.forms import EditResourceStoreForm
from resource.forms import EmitResourceStoreForm
from resource.forms import UpdateResourceStoreForm
from resource.models import ResourceFormats
from resource.models import Resource
from resource.redis_client import Handler as RedisHandler


CKAN_URL = settings.CKAN_URL
DIRECTORY_STORAGE = settings.DIRECTORY_STORAGE
DOMAIN = settings.DOMAIN_NAME
LOGIN_URL = settings.LOGIN_URL


decorators = [csrf_exempt, login_required(login_url=LOGIN_URL)]


@method_decorator(decorators, name='dispatch')
class ResourceStoreBaseView(View):

    def get(self, *args, **kwargs):
        raise NotImplementedError

    def post(self, *args, **kwargs):
        raise NotImplementedError

    def redis_create_key(self, user, instance_store, instance_store_pk, content_type):
        return RedisHandler().create(
            user=user.pk,
            content_type=content_type,
            name=instance_store.file_path.name,
            size=instance_store.file_path.size,
            filename=instance_store.file_path.path,
            related_pk=instance_store_pk,
            related_model=type(instance_store).__name__
        )

    def init_resource_form(self, instance_store, title, content_type, redis_key, resource=None):

        filters = [
            Q(mimetype__overlap=[content_type]),
            Q(extension=instance_store.file_path.name.split('.')[-1])
        ]
        format_type = ResourceFormats.objects.filter(reduce(ior, filters)).distinct().first()

        resource_form = CreateResourceStoreForm(
            # instance=resource,  # Si on veut recuperer les anciennes valeurs
            initial={
                'title': title,
                'language': 'french',
                'resource_type': 'annexe',
                'format_type': format_type,
                'redis_key': redis_key,
                'description': resource.description if resource else ''
            }
        )
        return resource_form


class EmitResourceStore(ResourceStoreBaseView):
    """Emettre un fichier pour la création d'une ressource de type Store."""

    def get(self, request, dataset_id=None, *args, **kwargs):
        user, profile = user_and_profile(request)
        dataset = get_object_or_404_extended(Dataset, user, include={'id': dataset_id})
        context = {
            'form': EmitResourceStoreForm(),
            'dataset': dataset,
        }
        return render_with_info_profile(request, 'resource/store/create.html', context)

    @transaction.atomic
    def post(self, request, dataset_id=None, *args, **kwargs):
        user, profile = user_and_profile(request)

        dataset = get_object_or_404_extended(Dataset, user, include={'id': dataset_id})
        form = EmitResourceStoreForm(data=request.POST, files=request.FILES)

        if not form.is_valid():
            context = {
                'form': EmitResourceStoreForm(),
                'dataset': dataset
            }
            return render_with_info_profile(request, 'resource/store/create.html', context)

        instance_store = form.save()

        content_type = request.FILES.get('file_path').content_type
        title = request.FILES.get('file_path').name

        # Création d'une entrée REDIS pour suivre la vie de la création de la ressource
        redis_key = self.redis_create_key(user, instance_store, instance_store.pk, content_type)

        resource_form = self.init_resource_form(instance_store, title, content_type, redis_key)

        context = {
            'form': resource_form,
            'dataset': dataset,
        }
        return render_with_info_profile(request, 'resource/create.html', context)


class UpdateResourceStore(ResourceStoreBaseView):
    """Emettre un nouveau fichier pour une ressource de type Store."""

    def get(self, request, dataset_id, resource_id, *args, **kwargs):

        user, profile = user_and_profile(request)

        dataset = get_object_or_404_extended(Dataset, user, include={'id': dataset_id})
        resource = get_object_or_404_extended(Resource, user, include={'id': resource_id})

        store = resource.store if hasattr(resource, 'store') else None
        context = {
            'form': UpdateResourceStoreForm(instance=store),
            'dataset': dataset,
            'resource': resource,
            'store': store
        }
        return render_with_info_profile(request, 'resource/store/update.html', context)

    @transaction.atomic
    def post(self, request, dataset_id, resource_id, *args, **kwargs):
        user, profile = user_and_profile(request)

        dataset = get_object_or_404_extended(Dataset, user, include={'id': dataset_id})
        resource = get_object_or_404_extended(Resource, user, include={'id': resource_id})

        old_store = resource.store
        # store = resource.store if hasattr(resource, 'store') else None
        form = UpdateResourceStoreForm(data=request.POST, files=request.FILES, instance=old_store)

        if not form.is_valid():
            context = {
                'form': EmitResourceStoreForm(),
                'dataset': dataset,
                'resource': resource,
                'store': old_store,
            }
            return render_with_info_profile(request, 'resource/store/update.html', context)

        # else:
        updated_store = form.save()

        content_type = request.FILES.get('file_path').content_type
        title = request.FILES.get('file_path').name

        # Création d'une entrée REDIS pour suivre la vie de la création de la ressource
        redis_key = self.redis_create_key(user, updated_store, updated_store.pk, content_type)

        resource_form = self.init_resource_form(updated_store, title, content_type, redis_key, resource)

        context = {
            'form': resource_form,
            'dataset': dataset,
            'resource': resource,
            'store': updated_store
        }
        return render_with_info_profile(request, 'resource/edit.html', context)


@method_decorator(decorators, name='dispatch')
class CreateResourceStore(View):
    """Créer une ressource de type Store."""

    @transaction.atomic
    def post(self, request, dataset_id=None, *args, **kwargs):
        user, profile = user_and_profile(request)

        dataset = get_object_or_404(Dataset, pk=dataset_id)
        form = CreateResourceStoreForm(data=request.POST)
        context = {
            'form': form,
            'dataset': dataset,
        }

        if not form.is_valid():
            return render_with_info_profile(request, 'resource/create_store.html', context)
        resource = form.save(dataset=dataset)

        save_ckan_resource(resource, with_user=user)

        msg = (
            'La ressource a été créée avec succès. '
            'Souhaitez-vous <a href="{0}">ajouter une nouvelle ressource</a> '
            'ou bien <a href="{1}" target="_blank">voir la ressource dans CKAN</a> ?'
        ).format(
            reverse('idgo_admin:resource', kwargs={'dataset_id': dataset.pk}),
            resource.ckan_url,
        )
        messages.success(request, msg)

        url_params = {
            'dataset_id': dataset_id,
            'resource_id': resource.pk
        }
        url = reverse('resource:show_resource_store', kwargs=url_params)
        return HttpResponseRedirect(url)


@method_decorator(decorators, name='dispatch')
class EditResourceStore(View):
    """Editer d'une resource de type Store."""

    EditForm = EditResourceStoreForm

    def get(self, request, dataset_id, resource_id, *args, **kwargs):
        user, profile = user_and_profile(request)

        dataset = get_object_or_404(Dataset, pk=dataset_id)
        resource = get_object_or_404(Resource, pk=resource_id)
        form = self.EditForm(instance=resource)

        context = {'form': form, 'dataset': dataset, 'resource': resource}
        return render_with_info_profile(request, 'resource/edit.html', context)

    @transaction.atomic
    def post(self, request, dataset_id, resource_id, *args, **kwargs):
        user, profile = user_and_profile(request)

resource/templates/resource/store/actions.html
<div class="buttons-on-the-right-side">
  <button type="button" class="btn btn-danger left" data-toggle="modal" data-target="#modal-resource-delete">Supprimer</button>
  <a class="btn btn-default" href="{{ resource.ckan_url }}" target="_blank">Voir la fiche CKAN</a>
  <a class="btn btn-primary" href="{% url 'resource:update_resource_store' dataset_id=dataset.pk resource_id=resource.pk %}">Mettre à jour le répertoire</a>
  <a class="btn btn-primary" href="{% url 'resource:edit_resource_store' dataset_id=dataset.pk resource_id=resource.pk %}">Éditer les informations</a>
</div>

<div class="modal fade" id="modal-resource-delete" tabindex="-1" role="dialog" aria-labelledby="ModalResourceDelete">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Êtes-vous absolument sûr ?</h4>
      </div>
      <div class="modal-body">
        <p>Cette action est irreversible et supprimera <strong>définitivement</strong> la ressource.</p>
        <p>Pour confirmer votre action, veuillez réécrire le nom complet de la ressource à supprimer :</p>
        <form>
          <input id="input-resource-delete" type="text" class="form-control" placeholder="Nom de la ressource à supprimer"></input>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default left" data-dismiss="modal">Annuler</button>
        <a id="button-resource-delete" class="btn btn-danger disabled" disable href="{% url 'resource:delete_resource_store' dataset_id=dataset.pk resource_id=resource.pk %}">
          Oui, supprimer définitivement cette ressource
        </a>
      </div>
    </div>
  </div>
</div>

<script>
$(function() {

  const $button = $('#button-resource-delete');
  const $input = $('#input-resource-delete');
  const $modal = $('#modal-resource-delete').modal({ 'backdrop': 'static', 'show': false });

  $input.on('input', function(evt) {
    evt.preventDefault();
    if ($(this).val().trim() === `{{ resource.title }}`) {
      $button.removeClass('disabled').prop('disable', false);
    } else {
      $button.addClass('disabled').prop('disable', true);
    };
  });

  $modal.on('hidden.bs.modal', function(evt) {
    evt.preventDefault();
    $input.val('');
  });

});
</script>

resource/templates/resource/store/create.html
{% extends "idgo_admin/base.html" %}

{% load bootstrap3 %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
  {% include "resource/breadcrumb_base.html" %}
  <li class="active">
    Nouveau répertoire de données
  </li>
</ol>
{% endblock breadcrumb_content %}

{% block main_content %}
<form method="post" action="{% url 'resource:emit_resource_store' dataset_id=dataset.id %}" enctype="multipart/form-data" class="well">
  {% csrf_token %}
  {% bootstrap_field form.file_path %}
  <div class="buttons-on-the-right-side">
    <a class="btn btn-default" href="{% url 'idgo_admin:dataset' %}?id={{ dataset.id }}#resources">Annuler</a>
    <button type="submit" class="btn btn-primary">Envoyer le fichier</button>
  </div>
</form>
{% endblock main_content %}

resource/templates/resource/store/extras.html
{% load resource_extras %}

<h4>URL vers l'API JSON offrant la liste complète des données du répertoire :</h4>
<table class="table table-bordered table-condensed">
  <tbody>
    <tr>
      <th style="width: 0">
        <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
      </th>
      <td>
        <a href="{% url 'resource:directory_storage' dataset_id=dataset.pk resource_id=resource.pk %}" target="_blank">
          http{% if request.is_secure %}s{% endif %}://{{ request.get_host }}{% url 'resource:directory_storage' dataset_id=dataset.pk resource_id=resource.pk %}</a>
      </td>
    </tr>
  </tbody>
</table>
<br />
<h4>Liste des fichiers disponibles :</h4>
<div class="table-responsive">
  <table class="table table-bordered table-condensed">
    <tbody>
      <tr>
        <th style="width: 0">
          <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
        </th>
        <th>URL</th>
        <th>Type MIME</th>
        <th>Taille</th>
      </tr>{% for file in files %}
      <tr>
        <th scope="row" style="text-align: center;">{{ forloop.counter }}</th>
        <td>
          <a href="{% url 'resource:directory_storage_glob' dataset_id=dataset.pk resource_id=resource.pk glob_path=file.path %}">
            http{% if request.is_secure %}s{% endif %}://{{ request.get_host }}{% url 'resource:directory_storage_glob' dataset_id=dataset.pk resource_id=resource.pk glob_path=file.path %}
          </a>
        </td>
        <td>
          {{ file.content_type }}
        </td>
        <td>
          {{ file.size|format_bytes }}
        </td>
      </tr>{% endfor %}
    </tbody>
  </table>
</div>

resource/templates/resource/store/update.html
{% extends "idgo_admin/base.html" %}

{% load bootstrap3 %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
  {% include "resource/breadcrumb_base.html" %}
  <li>
    <strong>{{ resource.title_overflow }}</strong>
  </li>
  <li>
    <strong>Mettre à jour le répertoire de données</strong>
  </li>
</ol>
{% endblock breadcrumb_content %}

{% block main_content %}
<form method="post" action="{% url 'resource:update_resource_store' dataset_id=dataset.id resource_id=resource.id %}" enctype="multipart/form-data" class="well">
  {% csrf_token %}
  {% bootstrap_field form.file_path %}
  <div class="buttons-on-the-right-side">
    <a class="btn btn-default" href="{% url 'idgo_admin:dataset' %}?id={{ dataset.id }}#resources">Annuler</a>
    <button type="submit" class="btn btn-primary">Enregistrer le fichier</button>
  </div>
</form>
{% endblock main_content %}