idgo_resource/urls.py
# Copyright (c) 2017-2020 Neogeo-Technologies.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


from django.conf.urls import url

from idgo_resource.views import CreateResourceFtp
from idgo_resource.views import CreateResourceUpload
from idgo_resource.views import Dashboard
from idgo_resource.views import DeleteResourceFtp
from idgo_resource.views import DeleteResourceUpload
from idgo_resource.views import EditResourceFtp
from idgo_resource.views import EditResourceUpload
from idgo_resource.views import EmitResourceFtp
from idgo_resource.views import EmitResourceUpload
from idgo_resource.views import NewResource
from idgo_resource.views import RedirectResource
from idgo_resource.views import ShowResourceFtp
from idgo_resource.views import ShowResourceUpload
from idgo_resource.views import UpdateResourceFtp
from idgo_resource.views import UpdateResourceUpload


urlpatterns = [
    url('^dataset/(?P<dataset_id>(\d+))/resource/dashboard/$', Dashboard.as_view(), name='dashboard'),

    url('^dataset/(?P<dataset_id>(\d+))/-/resource/$', RedirectResource.as_view(), name='redirect_resource'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/$', NewResource.as_view(), name='new_resource'),

    # Resource: Upload
    # ================
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/upload/$', EmitResourceUpload.as_view(), name='emit_resource_upload'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/upload/create/$', CreateResourceUpload.as_view(), name='create_resource_upload'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/upload/show/$', ShowResourceUpload.as_view(), name='show_resource_upload'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/upload/edit/$', EditResourceUpload.as_view(), name='edit_resource_upload'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/upload/update/$', UpdateResourceUpload.as_view(), name='update_resource_upload'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/upload/delete/$', DeleteResourceUpload.as_view(), name='delete_resource_upload'),

    # Resource: Ftp
    # =============
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/ftp/$', EmitResourceFtp.as_view(), name='emit_resource_ftp'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/new/ftp/create/$', CreateResourceFtp.as_view(), name='create_resource_ftp'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/ftp/show/$', ShowResourceFtp.as_view(), name='show_resource_ftp'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/ftp/edit/$', EditResourceFtp.as_view(), name='edit_resource_ftp'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/ftp/update/$', UpdateResourceFtp.as_view(), name='update_resource_ftp'),
    url('^dataset/(?P<dataset_id>(\d+))/resource/(?P<resource_id>(\d+))/ftp/delete/$', DeleteResourceFtp.as_view(), name='delete_resource_ftp'),
]

idgo_resource/models.py
# Copyright (c) 2017-2020 Neogeo-Technologies.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


from functools import reduce
import json
import os
import shutil
from urllib.parse import urljoin
import uuid

from django.conf import settings
from django.contrib.gis.db import models
from django.contrib.postgres.fields import ArrayField
from django.db.models.signals import post_delete
from django.db.models.signals import post_save
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone

from idgo_admin.ckan_module import CkanHandler
from idgo_admin.ckan_module import CkanUserHandler
from idgo_admin.managers import DefaultResourceManager
from idgo_admin.utils import three_suspension_points
from idgo_resource import logger


try:
    DOWNLOAD_SIZE_LIMIT = settings.DOWNLOAD_SIZE_LIMIT
except AttributeError:
    DOWNLOAD_SIZE_LIMIT = 104857600

if settings.STATIC_ROOT:
    locales_path = os.path.join(settings.STATIC_ROOT, 'mdedit/config/locales/fr/locales.json')
else:
    locales_path = os.path.join(settings.BASE_DIR, 'idgo_admin/static/mdedit/config/locales/fr/locales.json')

try:
    with open(locales_path, 'r', encoding='utf-8') as f:
        MDEDIT_LOCALES = json.loads(f.read())
        AUTHORIZED_PROTOCOL = (
            (protocol['id'], protocol['value']) for protocol
            in MDEDIT_LOCALES['codelists']['MD_LinkageProtocolCode'])
except Exception:
    AUTHORIZED_PROTOCOL = None

CKAN_STORAGE_PATH = settings.CKAN_STORAGE_PATH
OWS_URL_PATTERN = settings.OWS_URL_PATTERN
CKAN_URL = settings.CKAN_URL


# =======================
# Modèle RESOURCE FORMATS
# =======================


class ResourceFormats(models.Model):
    """Modèle de classe des formats de données des ressources."""

    class Meta(object):
        verbose_name = "Format de ressource"
        verbose_name_plural = "Formats de ressource"

    slug = models.SlugField(
        verbose_name="Slug",
        max_length=100,
        unique=True,
        db_index=True,
    )

    description = models.TextField(
        verbose_name="Description",
    )

    extension = models.CharField(
        verbose_name="Extension du fichier",
        max_length=10,
    )

    mimetype = ArrayField(
        models.TextField(),
        verbose_name="Type MIME",
        blank=True,
        null=True,
    )

    PROTOCOL_CHOICES = AUTHORIZED_PROTOCOL

    protocol = models.CharField(
        verbose_name="Protocole",
        max_length=100,
        blank=True,
        null=True,
        choices=PROTOCOL_CHOICES,
    )

    ckan_format = models.CharField(
        verbose_name="Format CKAN",
        max_length=10,
    )

    CKAN_CHOICES = (
        (None, 'N/A'),
        ('text_view', 'text_view'),
        ('geo_view', 'geo_view'),
        ('recline_view', 'recline_view'),
        ('pdf_view', 'pdf_view'),
    )

    ckan_view = models.CharField(
        verbose_name="Vue CKAN",
        max_length=100,
        blank=True,
        null=True,
        choices=CKAN_CHOICES,
    )

    is_gis_format = models.BooleanField(
        verbose_name="Format de fichier SIG",
        blank=False,
        null=False,
        default=False,
    )

    def __str__(self):
        return self.description


# ===============
# Modèle RESOURCE
# ===============


class Resource(models.Model):
    """Modèle de classe d'une ressource de données."""

    class Meta(object):
        verbose_name = "Ressource"
        verbose_name_plural = "Ressources"

    # Managers
    # ========

    objects = models.Manager()
    default = DefaultResourceManager()

    # Champs atributaires
    # ===================

    dataset = models.ForeignKey(
        to='idgo_admin.Dataset',
        related_name='idgo_resources',
        verbose_name="Jeu de données",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    ckan_id = models.UUIDField(
        verbose_name="Ckan UUID",
        default=uuid.uuid4,
        editable=False,
        unique=True,
    )

    title = models.TextField(
        verbose_name='Title',
    )

    description = models.TextField(
        verbose_name="Description",
        blank=True,
        null=True,
    )

    LANG_CHOICES = (
        ('french', "Français"),
        ('english', "Anglais"),
        ('italian', "Italien"),
        ('german', "Allemand"),
        ('other', "Autre"),
    )

    language = models.CharField(
        verbose_name="Langue",
        choices=LANG_CHOICES,
        default='french',
        max_length=10,
    )

    format_type = models.ForeignKey(
        to='ResourceFormats',
        verbose_name="Format",
        blank=False,
        null=True,
    )

    created_on = models.DateTimeField(
        verbose_name='Date de création de la resource',
        blank=True,
        null=True,
        default=timezone.now,
    )

    last_update = models.DateTimeField(
        verbose_name='Date de dernière modification de la resource',
        blank=True,
        null=True,
    )

    TYPE_CHOICES = (
        ('raw', "Données brutes"),
        ('annexe', "Documentation associée"),
        ('service', "Service"),
    )

    resource_type = models.CharField(
        verbose_name="Type de la ressource",
        choices=TYPE_CHOICES,
        max_length=10,
        default='raw',
    )

    def __str__(self):
        return self.title

    @property
    def title_overflow(self):
        return three_suspension_points(self.title)

    @property
    def ckan_url(self):
        return reduce(urljoin, [
            CKAN_URL,
            'dataset/',
            self.dataset.slug + '/',
            'resource/',
            str(self.ckan_id) + '/',
        ])

    @property
    def api_location(self):
        kwargs = {
            'dataset_name': self.dataset.slug,
            'resource_id': self.ckan_id,
        }
        return reverse('api:resource_show', kwargs=kwargs)


# ============
# Modèles liés
# ============


class StorageResource(models.Model):

    class Meta(object):
        verbose_name = "Ressource magasin"
        verbose_name_plural = "Ressources magasin"

    resource = models.OneToOneField(
        'idgo_resource.Resource',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    file_path = models.FileField(
        verbose_name="Fichier",
        blank=True,
        null=True,
        db_column='file',
    )


class AbstractResourceRelation(models.Model):
    """Classe abstraite de définition des relations entres ressource et modèles liés."""

    class Meta:
        abstract = True

    resource = models.OneToOneField(
        'idgo_resource.Resource',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )


class AbstractResourceSync(AbstractResourceRelation):
    """Classe abstraite de définition des ressources synchronisées."""

    class Meta:
        abstract = True

    synchronise = models.BooleanField(
        verbose_name="Synchronisation de données distante",
        default=False,
    )

    EXTRA_FREQUENCY_CHOICES = (
        ('5mn', "Toutes les 5 minutes"),
        ('15mn', "Toutes les 15 minutes"),
        ('20mn', "Toutes les 20 minutes"),
        ('30mn', "Toutes les 30 minutes"),
    )

    FREQUENCY_CHOICES = (
        ('1hour', "Toutes les heures"),
        ('3hours', "Toutes les trois heures"),
        ('6hours', "Toutes les six heures"),
        ('daily', "Quotidienne (tous les jours à minuit)"),
        ('weekly', "Hebdomadaire (tous les lundi)"),
        ('bimonthly', "Bimensuelle (1er et 15 de chaque mois)"),
        ('monthly', "Mensuelle (1er de chaque mois)"),
        ('quarterly', "Trimestrielle (1er des mois de janvier, avril, juillet, octobre)"),
        ('biannual', "Semestrielle (1er janvier et 1er juillet)"),
        ('annual', "Annuelle (1er janvier)"),
        ('never', "Jamais"),
    )

    sync_frequency = models.CharField(
        verbose_name="Fréquence de synchronisation",
        max_length=20,
        blank=True,
        null=True,
        choices=FREQUENCY_CHOICES + EXTRA_FREQUENCY_CHOICES,
        default='never',
    )

    url = models.URLField(
        verbose_name="Référencer une URL",
        max_length=2000,
        blank=True,
        null=True,
    )


def _ftp_file_upload_to(instance, filename):
    return filename


class AbstractResourceFile(AbstractResourceRelation):
    """Classe abstraite de définition des ressources contenant un fichier."""

    class Meta:
        abstract = True

    file_path = models.FileField(
        verbose_name="Fichier",
        blank=True,
        null=True,
        db_column='file',
        upload_to=_ftp_file_upload_to,
    )

    @property
    def get_file_url(self):
        if self.file_path and hasattr(self.file_path, 'url'):
            return self.file_path.url
        else:
            return None


class Href(AbstractResourceSync):
    """Modèle de classe les ressources référençant une URL."""

    class Meta(object):
        db_table = 'idgo_resource_href'
        verbose_name = "Ressource référençant une URL"
        verbose_name_plural = "Ressources référençant une URL"


class Download(AbstractResourceSync):
    """Modèle de classe les ressources téléchargées depuis une URL distante."""

    class Meta(object):
        db_table = 'idgo_resource_download'
        verbose_name = "Ressource Téléchargée depuis une URL distante"

idgo_resource/views/dashboard.py
# Copyright (c) 2017-2020 Neogeo-Technologies.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views import View

from idgo_admin.models import Dataset
from idgo_admin.shortcuts import render_with_info_profile
from idgo_admin.shortcuts import user_and_profile


decorators = [csrf_exempt, login_required(login_url=settings.LOGIN_URL)]


@method_decorator(decorators, name='dispatch')
class Dashboard(View):

    def get(self, request, dataset_id=None, *args, **kwargs):
        user, profile = user_and_profile(request)
        dataset = get_object_or_404(Dataset, pk=dataset_id)

        context = {
            'dataset': dataset,
        }

        return render_with_info_profile(request, 'resource/dashboard.html', context)

idgo_resource/templates/resource/breadcrumb_base.html
<li>
  <span class="glyphicon glyphicon-home"></span>
</li>
<li>
  Jeux de données
</li>
<li>
  <a href="{% url 'idgo_admin:dataset' %}?id={{ dataset.id }}#dataset">{{ dataset.title_overflow }}</a>
</li>
<li>
  <a href="{% url 'idgo_admin:dataset' %}?id={{ dataset.id }}#resources">Ressources</a>
</li>

idgo_resource/templates/resource/create.html
{% extends "idgo_admin/base.html" %}

{% load bootstrap3 %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
  {% include "resource/breadcrumb_base.html" %}
  <li class="active">
    Nouvelle ressource
  </li>
</ol>
{% endblock breadcrumb_content %}

{% block main_content %}
{% include "idgo_admin/alert_messages.html" %}
<form method="post" action="{% url 'idgo_resource:create_resource_store' dataset_id=dataset.id %}" class="well">
  {% csrf_token %}
  <div class="row">
    <div class="col-xs-12">
      {% bootstrap_field form.title %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      {% bootstrap_field form.description %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.language %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.resource_type %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.format_type %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 hidden">
      {% bootstrap_field form.redis_key %}
    </div>
  </div>
  <br />
  <div class="buttons-on-the-right-side">
    <a class="btn btn-default" href="{% url 'idgo_admin:dataset' %}?id={{ dataset.id }}#resources">Annuler</a>
    <button type="submit" class="btn btn-default">Valider la création</button>
  </div>
  <hr />
  <small>* Les champs marqués d'un astérisque sont obligatoires.</small>
</form>
{% endblock main_content %}

idgo_resource/templates/resource/dashboard.html
{% extends "idgo_admin/base.html" %}

{% load bootstrap3 %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
  {% include "resource/breadcrumb_base.html" %}
  <li class="active">
    Ajouter une ressource
  </li>
</ol>
{% endblock breadcrumb_content %}

{% block main_content %}
{% include "idgo_admin/alert_messages.html" %}
<span>Super Gut!</span>
{% endblock main_content %}

idgo_resource/templates/resource/edit.html
{% extends "idgo_admin/base.html" %}

{% load bootstrap3 %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
  {% include "resource/breadcrumb_base.html" %}
  <li>{{ resource.title }}</li>
  <li class="active">Editer la ressource</li>
</ol>
{% endblock breadcrumb_content %}

{% block main_content %}
{% include "idgo_admin/alert_messages.html" %}
<form method="post" action="{% url 'idgo_resource:edit_resource_store' dataset_id=dataset.id resource_id=resource.id%}" class="well">
  {% csrf_token %}
  <div class="row">
    <div class="col-xs-12">
      {% bootstrap_field form.title %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      {% bootstrap_field form.description %}
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.language %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.resource_type %}
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-xs-4">
      {% bootstrap_field form.format_type %}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 hidden">
      {% bootstrap_field form.redis_key %}
    </div>
  </div>
  <br />
  <div class="buttons-on-the-right-side">
    <a class="btn btn-default" href="{% url 'idgo_admin:dataset' %}?id={{ dataset.id }}#resources_store">Annuler</a>
    <button type="submit" class="btn btn-default">Valider la modification</button>
  </div>
  <hr />
  <small>* Les champs marqués d'un astérisque sont obligatoires.</small>
</form>
{% endblock main_content %}

idgo_resource/templates/resource/new.html
{% extends "idgo_admin/base.html" %}

{% load bootstrap3 %}

{% block breadcrumb_content %}
<ol class="breadcrumb">
  {% include "resource/breadcrumb_base.html" %}
  <li class="active">
    Ajouter une ressource
  </li>
</ol>
{% endblock breadcrumb_content %}

{% block main_content %}
<!-- <div class="row">
  <div class="col-md-3">
    <a role="button" class="btn btn-default btn-block btn-new-res-grid disabled" href="#">
      Référencer une URL
    </a>
  </div>
  <div class="col-md-3">
    <a role="button" class="btn btn-default btn-block btn-new-res-grid disabled" href="#">
      Synchroniser une URL de donnnées
    </a>
  </div>
  <div class="col-md-3">
    <a role="button" class="btn btn-default btn-block btn-new-res-grid" href="#">
      Téléverser un fichier
    </a>
  </div>
  <div class="col-md-3">
    <a role="button" class="btn btn-default btn-block btn-new-res-grid disabled" href="#">
      Synchroniser un fichier depuis le FTP
    </a>
  </div>
</div>
<hr> -->
{% for extension in RESOURCE_EXTENSIONS %}{% include extension.template with dataset_id=dataset.id %}{% endfor %}
{% endblock main_content %}

idgo_resource/templates/resource/show.html
<div>
  <h3>Informations concernant la ressource</h3>
  <table class="table table-bordered table-condensed">
    <thead>
      <tr>
        <th class="col-xs-4 col-sm-3 col-md-2 col-lg-2">Titre</th>
        <th class="col-xs-8 col-sm-9 col-md-10 col-lg-10">{{ resource.title }}</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th class="col-xs-4 col-sm-3 col-md-2 col-lg-2">Description</th>
        <td class="col-xs-8 col-sm-9 col-md-10 col-lg-10">{{ resource.description|default:"" }}</td>
      </tr>
      <tr>
        <th class="col-xs-4 col-sm-3 col-md-2 col-lg-2">Langue</th>
        <td class="col-xs-8 col-sm-9 col-md-10 col-lg-10">{{ resource.get_language_display }}</td>
      </tr>
      <tr>
        <th class="col-xs-4 col-sm-3 col-md-2 col-lg-2">Type de resource</th>
        <td class="col-xs-8 col-sm-9 col-md-10 col-lg-10">{{ resource.get_resource_type_display }}</td>
      </tr>
      <tr>
        <th class="col-xs-4 col-sm-3 col-md-2 col-lg-2">Format</th>
        <td class="col-xs-8 col-sm-9 col-md-10 col-lg-10">{{ resource.format_type.description }}</td>
      </tr>
    </tbody>
  </table>
</div>